### PR TITLE
Bump quiver version to 1.9

### PR DESCRIPTION
**Pull request by guidoiaquinti**

### CODE REVIEW

**Comment by abe-winter-4s** [comment]
any objection to targeting both 1.8 and 1.9? travis seems to allow multiple go versions: https://docs.travis-ci.com/user/languages/go/#Specifying-a-Go-version-to-use

**Comment by guidoiaquinti** [comment]
Yup, Travis supports multiple go versions and we can definitely make `quiver` ready for go +1.8 but I don't get the reason behind it.

**Comment by abe-winter-4s** [comment]
foursquare is on 1.8

**Comment by guidoiaquinti** [comment]
Us as well 😉 time to upgrade?

**Comment by guidoiaquinti** [comment]
If you can't upgrade let's add both 1.8 and 1.9, I'm 👍 for that. I'll wait for your feedback @abe-winter-4s

**Comment by abe-winter-4s** [comment]
@theevocater want to 👍 this plan?

**Comment by guidoiaquinti** [comment]
Any update @abe-winter-4s @theevocater ? 🙏

**Comment by guidoiaquinti** [comment]
Any update? [Go 1.10](https://golang.org/doc/go1.10) is out. 

FYI: we are running a `quiver` build with go 1.9.1 since months now, all ✅

**Review by mateor — APPROVED** [review]

**Comment by mateor** [comment]
Sorry, Quiver has a new maintainer (me) that wasn't aware of this PR.

We are on 1.9.3  so I can merge this as-is. We have some changes on the way for how we distribute this library (may add to https://github.com/foursquare/fsgo ) but will merge this now since we are a little ways from making any choice there.

**Comment by guidoiaquinti** [comment]
Awesome, thanks @mateor !

**Pull request merged**
