### PR TITLE
new option -no-copy-to-mem that serves from disk

### PR DESCRIPTION
**Pull request by slackhappy**
uses existing feature that was exposed for tests

performance seems pretty good, actually.  tested on a
large (2.2g) file that couldn't be malloc'd on my machine
and got ~3ms perf, which might be acceptable in some
scenarios

### CODE REVIEW

**Comment by slackhappy** [comment]
heh. that was 3ms from a very slow client (but, ya know... php... not known for speed).  Server stats:

```
.servehttp.count 506
.servehttp.min 0
.servehttp.max 1
.servehttp.mean 0.04
.servehttp.std-dev 0.05
.servehttp.percentiles.p50 0.04
.servehttp.percentiles.p90 0.05
.servehttp.percentiles.p95 0.06
.servehttp.percentiles.p99 0.09
.servehttp.percentiles.p999 1.04
.servehttp.one-minute 0.00
.servehttp.five-minute 0.12
.servehttp.fifteen-minute 0.30
.servehttp.mean 0.60
```

**Comment by slackhappy** [comment]
fixed the naming a bit: `-mnolock` instead of `-no-copy-to-mem`

**Comment by slackhappy** [comment]
read in (default)

```
./quiver collection=test.hfile
...
2016/06/09 16:05:22 Loading collections...
2016/06/09 16:05:22 [Reader.NewReader] Reading in collection (0.00mb)...
2016/06/09 16:05:22 [Reader.NewReader] Loaded collection.
...
```

mmap, no lock

```
./quiver -mnolock collection=test.hfile
...
2016/06/09 16:05:16 Loading collections...
2016/06/09 16:05:16 [Reader.NewReader] Serving collection from disk...
...
```

mmap, lock

```
./quiver -mlock collection=test.hfile
...
2016/06/09 16:05:00 Loading collections...
2016/06/09 16:05:00 [Reader.NewReader] Locking collection (0.00mb)...
2016/06/09 16:05:00 [Reader.NewReader] Locked collection.
...
```

**Comment by theevocater** [comment]
Hello again! I didn't realize this wasn't exposed at the command line. Thanks for piping it through, and sorry for the slow response!

**Pull request merged**
